name: corpusbattleofthebands
favicon: null
layout_spectrum: 0.3457872464787215
typography_spectrum: 0.32852
title: Corpus Battle of the Bands
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242021'
    - '#236271'
    - '#ffffff'
    - '#56abc8'
    - '#b6b4b5'
  brandStrength: 0.6036155098117888
  lightness: 0.17346982494927943
  saturation: 0.6843842705711722
  rhythmicContrast: 0.27395379403606057
purpose: []
